project:
  type: website

website:
  title: "Just Plain Data"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/rplain1
      - icon: bluesky
        href: https://bsky.app/profile/ryanplain.bsky.social
format:
  html:
    theme: cosmo
    css: styles.css
